name: Test
on:
  push:
    branches:       # Array of patterns that match refs/heads
      - main        # Push events on master branch
      - releases/*  # Push events to branches matching refs/heads/releases/*
  pull_request:     # Specify a second event with pattern matching
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      GO_VERSION: "1.22"
      MYSQL_VERSION: "8"
      POSTGRES_VERSION: "15"
      SQLSERVER_VERSION: "2022-latest"
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Test
      run: docker compose run goqu-coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        env_vars: OS,MYSQL_VERSION,POSTGRES_VERSION,SQLSERVER_VERSION
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
